Repository codeit-final-project-team3/GiveMeFive, pull requests merged in 2024-11, with the labels that each got.

#67 Fix : 체험 상세페이지
  src/app/(contents)/activities/[id]/activityinfo/ActivityInfo.module.scss
  src/app/(contents)/activities/[id]/activityinfo/ActivityInfo.tsx
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.tsx
Labels: fix

#66 Design: 로고 이미지 변경
  public/apple-touch-icon.png
  public/favicon-96x96.png
  public/favicon.ico
  public/favicon.svg
  public/site.webmanifest
  public/web-app-manifest-192x192.png
  public/web-app-manifest-512x512.png
  src/app/components/@shared/header/Header.tsx
  src/app/components/auth/Auth.tsx
  src/app/layout.tsx
  src/images/logos/logo-big.png
  src/images/logos/logo-md.png
Labels: feat

#69 Feature: 내 예약 현황 페이지 구현, 반응형 구현
  src/app/addactivities/addactivities.module.scss
  src/app/addactivities/page.tsx
  src/app/components/@shared/dropdown/Dropdown.tsx
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.module.scss
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.tsx
  src/app/components/addActivities/bannerImageInput/BannerImageInput.module.scss
  src/app/components/addActivities/dateTimeInput/DateTimeInput.module.scss
  src/app/components/addActivities/dateTimeInput/DateTimeInput.tsx
  src/app/components/addActivities/subImageInput/SubImageInput.module.scss
  src/app/components/myReservations/MyReservations.module.scss
  src/app/components/myReservations/MyReservations.tsx
  src/app/components/myReservations/ReservationCard/ReservationCard.module.scss
  src/app/components/myReservations/ReservationCard/ReservationCard.tsx
  src/app/components/myReservations/ReservationInfoModal/ReservationInfoModal.module.scss
  src/app/components/myReservations/ReservationInfoModal/ReservationInfoModal.tsx
  src/app/components/myReservations/ReservationInfoTabs/ReservationInfoTabs.module.scss
  src/app/components/myReservations/ReservationInfoTabs/ReservationInfoTabs.tsx
  src/app/components/myReservations/Reservations/Reservations.module.scss
  src/app/components/myReservations/Reservations/Reservations.tsx
  src/app/editactivities/[id]/page.tsx
  src/app/myreservationspage/myreservationspage.module.scss
  src/app/myreservationspage/page.tsx
  src/fetches/getReservationDashboard.ts
  src/fetches/patchResetvationsStatus.ts
  src/hooks/useDropdown.ts
  src/images/delete-X-button.svg
  src/usages/Dropdown.usage.md
Labels: feat

#70 #35 feat: 체험 등록 수정 페이지
  src/app/(contents)/editactivities/[id]/editActivities.module.scss
  src/app/(contents)/editactivities/[id]/page.tsx
  src/app/(contents)/mypage/myexperiencemanagement/addactivities/AddActivities.module.scss
  src/app/(contents)/mypage/myexperiencemanagement/addactivities/page.tsx
  src/app/(contents)/mypage/myexperiencemanagement/myexperienceManagement.module.scss
  src/app/(contents)/mypage/myexperiencemanagement/page.tsx
  src/app/(contents)/mypage/myprofile/page.tsx
  src/app/(contents)/mypage/reservationhistory/page.tsx
  src/app/(contents)/myreservations/myreservations.module.scss
  src/app/(contents)/myreservations/page.tsx
  src/app/components/@shared/modal/AlertModal.module.scss
  src/app/components/@shared/modal/AlertModal.tsx
  src/app/components/@shared/modal/ConfirmModal.module.scss
  src/app/components/@shared/modal/ConfirmModal.tsx
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.tsx
  src/app/components/mypage/SideMenu.tsx
  src/images/add-plus-button.svg
  src/images/dropdown-arrow.svg
  src/images/logos/logo-big.svg
  src/images/logos/logo-md.svg
  src/images/sidemenuIcon/profile-button-icon.svg
  src/styles/abstracts/_colors.scss
Labels: feat

#71 #35 Fix: 캘린더 스타일 수정
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
Labels: fix

#72 #35 Fix: 캘린더 스타일 수정
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
Labels: fix

#74 Hotfix: ReservationCalendar의 mantineCalendarClassNames 프로퍼티의 타입 수정
  src/app/components/@shared/reservationCalendar/ReservationCalendar.tsx
Labels: fix

#73 #46/fix/mainpage
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.tsx
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.module.scss
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/banner/Banner.module.scss
  src/app/(contents)/mainpage/banner/Banner.tsx
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.module.scss
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.tsx
  src/app/(contents)/page.tsx
Labels: fix, refactor

#76 Fix: 캘린더 버그 수정
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
  src/app/components/reservation/ResponsiveReservation.tsx
  src/hooks/useReservationSubmit.ts
  src/queries/useAvailableScheduleQuery.ts
  src/stores/useReservationStore.ts
  src/types/reservation.ts
Labels: fix

#78 Fix: 예약 현황, 내 체험 등록 버그 수정
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.module.scss
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.tsx
  src/app/components/addActivities/bannerImageInput/BannerImageInput.module.scss
  src/app/components/addActivities/dateTimeInput/DateTimeInput.tsx
  src/app/components/addActivities/daumAdress/DaumAddress.module.scss
  src/app/components/addActivities/daumAdress/DaumAddress.tsx
  src/app/components/addActivities/subImageInput/SubImageInput.module.scss
  src/app/components/myReservations/ReservationInfoModal/ReservationInfoModal.module.scss
  src/app/components/myReservations/ReservationInfoModal/ReservationInfoModal.tsx
  src/app/components/myReservations/Reservations/Reservations.module.scss
  src/app/components/myReservations/Reservations/Reservations.tsx
Labels: fix

#84 #83 Refactor: Header 자동 유저 정보 업데이트 로직 주석 및 코드 개선
  src/app/components/@shared/header/Header.tsx
Labels: refactor

#86 Refactor: 공통 Input 컴포넌트에 기본 input의 props 모두 받을 수 있도록 개선 및 usage 수정
  src/app/components/@shared/input/Input.tsx
  src/usages/Input.usage.md
Labels: refactor

#82 Fix : nomadBlack 색상 navy 변경
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/(contents)/mainpage/allzonecard/category/CategoryAndDropdown.module.scss
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.module.scss
  src/app/(contents)/mainpage/search/Search.module.scss
  src/app/(contents)/mainpage/search/Search.tsx
  src/app/(contents)/mypage/myexperiencemanagement/page.tsx
  src/app/components/@shared/button/Button.module.scss
  src/app/components/@shared/button/Button.tsx
  src/app/components/@shared/footer/Footer.module.scss
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
  src/app/components/reservation/AvailableTimeList.module.scss
  src/images/footerIcon/facebook-Icon.svg
  src/images/footerIcon/instagram-Icon.svg
  src/images/footerIcon/twitter-Icon.svg
  src/images/footerIcon/youtube-Icon.svg
  src/images/sidemenuIcon/profile-button-icon.svg
  src/styles/abstracts/_colors.scss
Labels: refactor

#81 Fix: 마이 페이지 카드 반응형, 모달 버튼 너비 버그 수정
  src/app/(contents)/editactivities/[id]/editActivities.module.scss
  src/app/(contents)/mypage/myexperiencemanagement/addactivities/AddActivities.module.scss
  src/app/(contents)/mypage/myexperiencemanagement/myexperienceManagement.module.scss
  src/app/(contents)/mypage/myprofile/myprofile.module.scss
  src/app/(contents)/myreservations/myreservations.module.scss
  src/app/components/@shared/modal/AlertModal.module.scss
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
  src/app/components/mypage/MyExperienceManagementCard.module.scss
  src/app/components/mypage/ReservationHistoryCard.module.scss
Labels: fix

#88 Fix: 리팩토링 도중 잘못된 로직 수정 및 헤더 로고 크기 조정
  src/app/components/@shared/header/Header.module.scss
  src/app/components/@shared/header/Header.tsx
Labels: refactor

#79 Fix : 메인페이지
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.tsx
  src/app/(contents)/activities/[id]/activityreviews/pagination/Pagination.module.scss
  src/app/(contents)/layout.module.scss
  src/app/(contents)/layout.tsx
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/banner/Banner.module.scss
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.module.scss
Labels: refactor

#87 Fix: 체험 등록/수정 페이지 디자인 수정, 예약현황 페이지 디자인 수정
  src/app/components/addActivities/dateTimeInput/DateTimeInput.tsx
  src/app/components/myReservations/ReservationInfoModal/ReservationInfoModal.tsx
  src/app/components/myReservations/ReservationInfoTabs/ReservationInfoTabs.module.scss
  src/app/components/myReservations/ReservationInfoTabs/ReservationInfoTabs.tsx
  src/app/components/myReservations/Reservations/Reservations.tsx
Labels: fix

#89 Fix : Loader 공통컴포넌트 분리 및 메인페이지 적용
  src/app/(contents)/page.tsx
  src/app/components/@shared/loader/Loader.module.scss
  src/app/components/@shared/loader/Loader.tsx
Labels: fix, refactor

#91 Fix : loader z-index 추가
  src/app/components/@shared/loader/Loader.module.scss
Labels: fix

#92 Fix: 드롭다운 외부 클릭 시 닫히지 않던 버그 수정
  src/app/components/@shared/dropdown/Dropdown.module.scss
  src/app/components/@shared/dropdown/Dropdown.tsx
  src/app/components/myReservations/Reservations/Reservations.tsx
Labels: fix

#96 Refactor: next image로 변경
  src/app/(contents)/mypage/myexperiencemanagement/page.tsx
  src/app/components/mypage/MyExperienceManagementCard.tsx
  src/app/components/mypage/MyExperienceManagementList.module.scss
  src/app/components/mypage/ReservationHistoryCard.tsx
  src/app/components/mypage/ReservationHistoryCardList.module.scss
  src/app/components/mypage/ReservationHistoryCardList.tsx
Labels: refactor

#97 Feature : metadata 오픈그래프
  src/app/layout.tsx
  src/app/loading.module.scss
Labels: feat

#98 Fix: 불필요 코드 삭제
  src/app/components/@shared/dropdown/Dropdown.module.scss
  src/app/components/@shared/dropdown/Dropdown.tsx
  src/app/components/myReservations/ReservationCard/ReservationCard.tsx
  src/app/components/myReservations/Reservations/Reservations.tsx
Labels: fix, refactor

#105 Fix: 애니메이션 추가, 사이드메뉴 버튼 범위 수정
  src/app/components/mypage/MyExperienceManagementList.module.scss
  src/app/components/mypage/MyExperienceManagementList.tsx
  src/app/components/mypage/ReservationHistoryCardList.module.scss
  src/app/components/mypage/ReservationHistoryCardList.tsx
  src/app/components/mypage/SideMenu.module.scss
  src/app/layout.tsx
Labels: fix

#102 Feature: 컴포넌트 작성 없이 함수 호출로 전역에서 사용 가능한 선언형 토스트 팝업 구현
  src/app/components/@shared/portal/Portal.tsx
  src/app/components/auth/SignupForm.tsx
  src/app/components/providers/Providers.tsx
  src/app/components/providers/ToastProvider.tsx
  src/app/components/toast/Toast.module.scss
  src/app/components/toast/Toast.tsx
  src/app/components/toast/ToastList.module.scss
  src/app/components/toast/ToastList.tsx
  src/app/layout.tsx
  src/images/icons/icon-error.svg
  src/images/icons/icon-success.svg
  src/images/icons/icon-warn.svg
  src/stores/useToastStore.ts
  src/styles/abstracts/_animations.scss
  src/styles/abstracts/_colors.scss
  src/styles/abstracts/_core.scss
  src/styles/abstracts/_keyframes.scss
  src/styles/abstracts/_variables.scss
  src/types/toast.ts
  src/usages/useToast.uage.md
Labels: feat

#99 Fix : 리펙토링 및 build 에러 처리
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/search/Search.tsx
  src/utils/getUrl.ts
Labels: fix, refactor

#107 #35 Fix: 카드리스트 모달 버그 수정
  src/app/(contents)/mypage/myexperiencemanagement/addactivities/page.tsx
  src/app/components/mypage/MyExperienceManagementList.tsx
Labels: fix

#106 Fix: AddActivitiesForm버그 수정, UI 수정
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.tsx
  src/app/components/addActivities/bannerImageInput/BannerImageInput.tsx
  src/app/components/addActivities/dateTimeInput/DateTimeInput.module.scss
  src/app/components/addActivities/dateTimeInput/DateTimeInput.tsx
  src/app/components/addActivities/daumAdress/DaumAddress.tsx
  src/app/components/addActivities/subImageInput/SubImageInput.tsx
  src/types/addActivities.ts
Labels: fix
