Repository codeit-final-project-team3/GiveMeFive, pull requests merged in 2024-10, with the labels that each got.

#9 Feature: 유효성 검사 기능 및 라벨, 에러 메시지 표출이 가능한 공용 Input 컴포넌트 제작
  package-lock.json
  package.json
  src/app/components/@shared/input/Input.module.scss
  src/app/components/@shared/input/Input.tsx
  src/constants/validOption.ts
  src/hooks/useValidForm.ts
  src/styles/base/globals.scss
  src/usages/Input.usage.md
Labels: feat

#10 Feature: ConfirmModal, AlertModal 공용 컴포넌트 제작
  package-lock.json
  package.json
  src/app/components/modal/AlertModal.scss
  src/app/components/modal/AlertModal.tsx
  src/app/components/modal/ConfirmModal.scss
  src/app/components/modal/ConfirmModal.tsx
  src/app/components/mypage/SideMenu.module.scss
  src/app/components/mypage/SideMenu.tsx
  src/app/components/mypage/UserInfoForm.module.scss
  src/app/components/mypage/UserInfoForm.tsx
  src/app/layout.tsx
  src/app/mypage/myexperiencemanagement/page.tsx
  src/app/mypage/mypage.module.scss
  src/app/mypage/myprofile/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/reservationhistory/page.tsx
  src/styles/abstracts/_mixins.scss
  src/styles/base/globals.scss
  src/usages/Modal.usage.md
Labels: feat

#11 Feature: 공용 Dropdown 컴포넌트 제작
  src/component/Dropdown/Dropdown.module.scss
  src/component/Dropdown/Dropdown.tsx
  src/hooks/useDropdown.ts
  src/images/dropdown-arrow.svg
  src/images/kebab-icon.svg
  src/usages/Dropdown.usage.md
Labels: feat

#12 Feature: 공용 컴포넌트 버튼 제작
  src/app/components/Button/Button.module.scss
  src/app/components/Button/Button.tsx
  src/usages/Button.usage.md
Labels: feat

#5 Feature: 공용 컴포넌트 footer 제작
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/components/Footer/Footer.module.scss
  src/app/components/Footer/Footer.tsx
  src/images/footerIcon/facebook-Icon.svg
  src/images/footerIcon/instagram-Icon.svg
  src/images/footerIcon/twitter-Icon.svg
  src/images/footerIcon/youtube-Icon.svg
Labels: feat

#13 Fix: 컨벤션 합의에 따른 폴더 명, 폴더 위치 수정
  src/app/components/dropdown/Dropdown.module.scss
  src/app/components/dropdown/Dropdown.tsx
Labels: feat

#15 Fix : 폴더명 변경
  src/app/(contents)/layout.tsx
  src/app/(contents)/page.tsx
  src/app/components/button/Button.module.scss
  src/app/components/button/Button.tsx
  src/app/components/footer/Footer.module.scss
  src/app/components/footer/Footer.tsx
Labels: fix

#20 Feature: 유저 기능 구현 및 로그인, 회원가입 페이지 제작
  middleware.ts
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/components/auth/Auth.module.scss
  src/app/components/auth/Auth.tsx
  src/app/components/auth/LoginForm.tsx
  src/app/components/auth/SignupForm.tsx
  src/fetches/login.ts
  src/fetches/setupAxios.ts
  src/fetches/signup.ts
  src/hooks/usePersistStore.ts
  src/hooks/useToggle.ts
  src/images/logo/logo-big.svg
  src/images/logo/logo-google.svg
  src/images/logo/logo-kakao.svg
  src/stores/useUserStore.ts
  src/styles/abstracts/_mixins.scss
  src/types/auth.ts
  src/types/user.ts
  src/utils/getTokens.ts
Labels: feat

#24 Feature: 헤더, 자동 로그인 기능 구현
  src/app/components/@shared/header/Header.module.scss
  src/app/components/@shared/header/Header.tsx
  src/app/components/@shared/header/LoggedInContainer.module.scss
  src/app/components/@shared/header/LoggedInContainer.tsx
  src/app/components/auth/Auth.tsx
  src/app/components/providers/Providers.tsx
  src/app/components/providers/QueryProvider.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/constants/queryKeys.ts
  src/fetches/getUserInfo.ts
  src/fetches/setupAxios.ts
  src/hooks/usePersistStore.ts
  src/images/icons/Icon-notification.svg
  src/images/logos/logo-big.svg
  src/images/logos/logo-google.svg
  src/images/logos/logo-kakao.svg
  src/images/logos/logo-md.svg
  src/images/profiles/default-profile.svg
  src/middleware.ts
  src/queries/useUserQuery.ts
  src/stores/useUserStore.ts
  src/styles/abstracts/_variables.scss
  src/styles/base/globals.scss
Labels: feat, refactor

#25 Feature: Dropdown 컴포넌트 기능 추가
  .gitignore
  src/app/components/@shared/dropdown/Dropdown.module.scss
  src/app/components/@shared/dropdown/Dropdown.tsx
  src/hooks/useDropdown.ts
  src/images/dropdown-thin-arrow.svg
  src/usages/Dropdown.usage.md
Labels: feat, refactor

#27 Feature: 내 체험 관리 페이지 구현
  next.config.mjs
  src/app/components/@shared/modal/AlertModal.module.scss
  src/app/components/@shared/modal/AlertModal.tsx
  src/app/components/mypage/MyExperienceManagementCard.module.scss
  src/app/components/mypage/MyExperienceManagementCard.tsx
  src/app/components/mypage/MyExperienceManagementList.module.scss
  src/app/components/mypage/MyExperienceManagementList.tsx
  src/app/mypage/myexperiencemanagement/myexperienceManagement.module.scss
  src/app/mypage/myexperiencemanagement/page.tsx
Labels: feat

#32 #31 Feat: modal 컴포넌트 제작
  src/app/components/@shared/modal/Modal.module.scss
  src/app/components/@shared/modal/Modal.tsx
  src/app/mypage/reservationhistory/page.tsx
  src/images/modal/close-button.svg
  src/usages/Modal.usage.md
Labels: feat

#28 Feature: 소셜 간편 회원가입 및 로그인 기능 구현 및 유저 기능 코드 점검
  next.config.mjs
  src/app/(auth)/oauth/google/page.tsx
  src/app/(auth)/oauth/google/signup/[token]/page.tsx
  src/app/(auth)/oauth/kakao/page.tsx
  src/app/(auth)/oauth/kakao/signup/[token]/page.tsx
  src/app/components/@shared/header/Header.tsx
  src/app/components/@shared/header/LoggedInContainer.module.scss
  src/app/components/auth/Auth.module.scss
  src/app/components/auth/Auth.tsx
  src/app/components/auth/AuthForm.module.scss
  src/app/components/auth/LoginForm.tsx
  src/app/components/auth/SignupForm.tsx
  src/app/components/auth/SocialAuth.module.scss
  src/app/components/auth/SocialAuth.tsx
  src/app/components/auth/SocialSignupNicknameForm.module.scss
  src/app/components/auth/SocialSignupNicknameForm.tsx
  src/constants/oauth.ts
  src/fetches/getGoogleJWT.ts
  src/fetches/oauthSignin.ts
  src/fetches/oauthSignup.ts
  src/queries/useUserQuery.ts
  src/stores/useUserStore.ts
  src/styles/base/globals.scss
  src/types/oauth.ts
  src/types/user.ts
Labels: feat, refactor

#33 Feature: 체험 등록 페이지 제작
  package-lock.json
  package.json
  src/app/addactivities/addactivities.module.scss
  src/app/addactivities/page.js
  src/app/components/@shared/dropdown/Dropdown.module.scss
  src/app/components/@shared/dropdown/Dropdown.tsx
  src/app/components/@shared/input/Input.tsx
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.module.scss
  src/app/components/addActivities/addActivitiesForm/AddActivitiesForm.tsx
  src/app/components/addActivities/bannerImageInput/BannerImageInput.module.scss
  src/app/components/addActivities/bannerImageInput/BannerImageInput.tsx
  src/app/components/addActivities/dateTimeInput/DateTimeInput.module.scss
  src/app/components/addActivities/dateTimeInput/DateTimeInput.tsx
  src/app/components/addActivities/daumAdress/DaumAddress.module.scss
  src/app/components/addActivities/daumAdress/DaumAddress.tsx
  src/app/components/addActivities/subImageInput/SubImageInput.module.scss
  src/app/components/addActivities/subImageInput/SubImageInput.tsx
  src/app/components/addActivities/textarea/Textarea.module.scss
  src/app/components/addActivities/textarea/Textarea.tsx
  src/app/layout.tsx
  src/app/mybookingstatus/mybookingstatus.module.scss
  src/app/mybookingstatus/page.js
  src/constants/validOption.ts
  src/fetches/createImageUrl.ts
  src/fetches/postActivities.ts
  src/hooks/useValidForm.ts
  src/images/add-plus-button.svg
  src/images/delete-button.svg
  src/images/delete-minus-button.svg
  src/images/plus-icon.svg
  src/types/addActivities.ts
  src/usages/Dropdown.usage.md
  src/usages/Input.usage.md
Labels: feat

#29 Feature: 메인 페이지
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.module.scss
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/allzonecard/category/CategoryAndDropdown.module.scss
  src/app/(contents)/mainpage/allzonecard/category/CategoryAndDropdown.tsx
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.module.scss
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.tsx
  src/app/(contents)/mainpage/banner/Banner.module.scss
  src/app/(contents)/mainpage/banner/Banner.tsx
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.module.scss
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.tsx
  src/app/(contents)/mainpage/bestzonecard/arrowButton/ArrowButton.module.scss
  src/app/(contents)/mainpage/bestzonecard/arrowButton/ArrowButton.tsx
  src/app/(contents)/mainpage/main.module.scss
  src/app/(contents)/mainpage/main.tsx
  src/app/(contents)/mainpage/search/Search.module.scss
  src/app/(contents)/mainpage/search/Search.tsx
  src/app/(contents)/page.tsx
  src/app/components/@shared/header/Header.module.scss
  src/fetches/activities.ts
  src/images/arrowleft-black.svg
  src/images/arrowleft-gray.svg
  src/images/arrowright-black.svg
  src/images/arrowright-gray.svg
  src/images/bed-icon.svg
  src/images/empty.svg
  src/images/star-icon.svg
  src/queries/useActivityQuery.ts
  src/styles/abstracts/_fonts.scss
  src/styles/abstracts/_mixins.scss
Labels: feat

#40 Feature : 메인페이지
  src/app/mainpage/allzonecard/AllZoneCard.tsx
  src/app/mainpage/bestzonecard/BestZoneCard.tsx
Labels: fix

#44 #3 design: 드롭다운 위치 수정
  src/app/components/@shared/dropdown/Dropdown.module.scss
Labels: fix

#45 Fix: Hide 드롭다운 디자인 수정
  src/app/components/@shared/dropdown/Dropdown.module.scss
Labels: fix

#46 Fix: 카카오 로그인 실패 시 회원 가입 연동 로직 수정
  src/app/(auth)/oauth/kakao/page.tsx
  src/app/(auth)/oauth/kakao/signup/page.tsx
  src/app/components/@shared/header/LoggedInContainer.tsx
  src/constants/oauth.ts
  src/fetches/oauthSignup.ts
Labels: fix

#39 Feature: 마이 페이지 기능 구현 및 api 연동
  src/app/components/mypage/MyExperienceManagementCard.tsx
  src/app/components/mypage/MyExperienceManagementList.tsx
  src/app/components/mypage/ReservationHistoryCard.module.scss
  src/app/components/mypage/ReservationHistoryCard.tsx
  src/app/components/mypage/ReservationHistoryCardList.module.scss
  src/app/components/mypage/ReservationHistoryCardList.tsx
  src/app/components/mypage/SideMenu.module.scss
  src/app/components/mypage/SideMenu.tsx
  src/app/components/mypage/UserInfoForm.tsx
  src/app/mypage/myexperiencemanagement/page.tsx
  src/app/mypage/reservationhistory/page.tsx
  src/app/mypage/reservationhistory/reservationhistory.module.scss
  src/fetches/myActivities.ts
  src/fetches/patchUserInfo.ts
  src/fetches/postProfileImage.ts
  src/fetches/reservationHistory.ts
  src/images/sidemenuIcon/profile-image.svg
  src/queries/useMyActivitiesQuery.ts
Labels: feat

#41 Feature : 체험 상세페이지
  src/app/activities/[id]/activity.module.scss
  src/app/activities/[id]/activityinfo/ActivityInfo.module.scss
  src/app/activities/[id]/activityinfo/ActivityInfo.tsx
  src/app/activities/[id]/activityinfo/map.tsx
  src/app/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/activities/[id]/activityreviews/ActivityReviews.tsx
  src/app/activities/[id]/activityreviews/pagination/Pagination.module.scss
  src/app/activities/[id]/activityreviews/pagination/Pagination.tsx
  src/app/activities/[id]/page.tsx
  src/fetches/activities.ts
  src/fetches/activitiesReviews.ts
  src/images/location.svg
  src/queries/useActivityInfoQuery.ts
  src/styles/abstracts/_fonts.scss
  src/styles/abstracts/_mixins.scss
Labels: feat

#42 Feat: 예약 날짜 및 시간, 인원 선택 컴포넌트 구현
  src/app/components/@shared/footer/Footer.module.scss
  src/app/components/@shared/header/Header.module.scss
  src/app/components/@shared/reservationCalendar/ReservationCalendar.module.scss
  src/app/components/@shared/reservationCalendar/ReservationCalendar.tsx
  src/app/components/providers/MantineProviders.tsx
  src/app/components/providers/Providers.tsx
  src/app/components/reservation/AvailableTimeList.module.scss
  src/app/components/reservation/AvailableTimeList.tsx
  src/app/components/reservation/CalendarModal.module.scss
  src/app/components/reservation/CalendarModal.tsx
  src/app/components/reservation/HeadCountStepper.module.scss
  src/app/components/reservation/HeadCountStepper.tsx
  src/app/components/reservation/MobileReservation.module.scss
  src/app/components/reservation/MobileReservation.tsx
  src/app/components/reservation/Reservation.module.scss
  src/app/components/reservation/Reservation.tsx
  src/app/components/reservation/ReservationModal.module.scss
  src/app/components/reservation/ReservationModal.tsx
  src/app/components/reservation/ReservationSelector.module.scss
  src/app/components/reservation/ReservationSelector.tsx
  src/app/components/reservation/ResponsiveReservation.tsx
  src/app/layout.tsx
  src/constants/queryKeys.ts
  src/fetches/getAvailableSchedule.ts
  src/fetches/submitReservation.ts
  src/hooks/useReservationSubmit.ts
  src/hooks/useToggle.ts
  src/images/icons/icon-add.svg
  src/images/icons/icon-subtract.svg
  src/queries/useAvailableScheduleQuery.ts
  src/queries/useReservationsMutation.ts
  src/stores/useReservationStore.ts
  src/styles/abstracts/_mixins.scss
  src/styles/abstracts/_variables.scss
  src/types/reservation.ts
  src/types/schedule.ts
  src/utils/getCurrencyFormat.ts
Labels: feat

#51 Feature : 마이 페이지 구현
  package-lock.json
  package.json
  src/app/components/@shared/modal/AlertModal.tsx
  src/app/components/@shared/modal/Modal.tsx
  src/app/components/mypage/MyExperienceManagementCard.module.scss
  src/app/components/mypage/MyExperienceManagementCard.tsx
  src/app/components/mypage/MyExperienceManagementList.module.scss
  src/app/components/mypage/MyExperienceManagementList.tsx
  src/app/components/mypage/ReservationHistoryCard.module.scss
  src/app/components/mypage/ReservationHistoryCard.tsx
  src/app/components/mypage/ReservationHistoryCardList.module.scss
  src/app/components/mypage/ReservationHistoryCardList.tsx
  src/app/components/mypage/StarRating.tsx
  src/app/components/mypage/WriteReview.module.scss
  src/app/components/mypage/WriteReview.tsx
  src/fetches/activitiesReviews.ts
Labels: feat

#50 Feature: Polling을 활용한 알림 기능 구현
  src/app/components/@shared/backdrop/BackDrop.module.scss
  src/app/components/@shared/backdrop/BackDrop.tsx
  src/app/components/@shared/header/Alarm.module.scss
  src/app/components/@shared/header/Alarm.tsx
  src/app/components/@shared/header/LoggedInContainer.module.scss
  src/app/components/@shared/header/LoggedInContainer.tsx
  src/app/components/@shared/header/notification/NotificationCard.module.scss
  src/app/components/@shared/header/notification/NotificationCard.tsx
  src/app/components/@shared/header/notification/NotificationModal.module.scss
  src/app/components/@shared/header/notification/NotificationModal.tsx
  src/constants/queryKeys.ts
  src/fetches/deleteNotifications.ts
  src/fetches/getNotifications.ts
  src/images/icons/icon-close-black.svg
  src/images/icons/icon-close-gray.svg
  src/images/sidemenuIcon/profile-image 2.svg
  src/queries/useNotification.ts
  src/queries/useNotificationDelete.ts
  src/styles/abstracts/_mixins.scss
  src/styles/abstracts/_variables.scss
  src/types/notifications.ts
  src/utils/getElapsedPeriod.ts
Labels: feat, fix, refactor

#53 Fix: ReservationCalendar 컴포넌트에서 mantine 스타일 받을 수 있도록 개선
  src/app/components/@shared/reservationCalendar/ReservationCalendar.tsx
Labels: fix

#54 #17/feature/mainpage
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.module.scss
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/allzonecard/category/CategoryAndDropdown.module.scss
  src/app/(contents)/mainpage/allzonecard/category/CategoryAndDropdown.tsx
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.module.scss
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.tsx
  src/app/(contents)/mainpage/banner/Banner.module.scss
  src/app/(contents)/mainpage/banner/Banner.tsx
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.module.scss
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.tsx
  src/app/(contents)/mainpage/bestzonecard/arrowButton/ArrowButton.module.scss
  src/app/(contents)/mainpage/bestzonecard/arrowButton/ArrowButton.tsx
  src/app/(contents)/mainpage/main.module.scss
  src/app/(contents)/mainpage/main.tsx
  src/app/(contents)/mainpage/search/Search.module.scss
  src/app/(contents)/mainpage/search/Search.tsx
  src/app/(contents)/page.tsx
Labels: fix

#56 Feature : 체험 상세 페이지
  src/app/(contents)/activities/[id]/activity.module.scss
  src/app/(contents)/activities/[id]/activityinfo/ActivityInfo.module.scss
  src/app/(contents)/activities/[id]/activityinfo/ActivityInfo.tsx
  src/app/(contents)/activities/[id]/activityinfo/map.tsx
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.tsx
  src/app/(contents)/activities/[id]/activityreviews/pagination/Pagination.module.scss
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/banner/Banner.tsx
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.tsx
  src/app/(contents)/mainpage/main.tsx
  src/app/(contents)/mainpage/search/Search.tsx
  src/fetches/activitiesReviews.ts
  src/images/arrow-left.svg
  src/images/arrow-right.svg
  src/queries/useActivityQuery.ts
  src/stores/useUserStore.ts
  src/types/user.ts
Labels: feat

#57 Feature: 반응형 페이지 구현
  package-lock.json
  package.json
  src/app/components/mypage/MyExperienceManagementCard.module.scss
  src/app/components/mypage/MyExperienceManagementList.tsx
  src/app/components/mypage/ReservationHistoryCard.module.scss
  src/app/components/mypage/ReservationHistoryCardList.module.scss
  src/app/components/mypage/ReservationHistoryCardList.tsx
  src/app/components/mypage/SideMenu.module.scss
  src/app/components/mypage/SideMenu.tsx
  src/app/components/mypage/StarRating.tsx
  src/app/components/mypage/UserInfoForm.module.scss
  src/app/components/mypage/UserInfoForm.tsx
  src/app/mypage/myexperiencemanagement/myexperienceManagement.module.scss
  src/app/mypage/myprofile/myprofile.module.scss
  src/app/mypage/reservationhistory/reservationhistory.module.scss
  src/fetches/myActivities.ts
Labels: feat

#55 Feature : 메인페이지
  src/app/(contents)/activities/[id]/activityinfo/ActivityInfo.module.scss
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.module.scss
  src/app/(contents)/activities/[id]/activityreviews/ActivityReviews.tsx
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.module.scss
  src/app/(contents)/mainpage/allzonecard/AllZoneCard.tsx
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.module.scss
  src/app/(contents)/mainpage/allzonecard/pagination/Pagination.tsx
  src/app/(contents)/mainpage/banner/Banner.module.scss
  src/app/(contents)/mainpage/banner/Banner.tsx
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.module.scss
  src/app/(contents)/mainpage/bestzonecard/BestZoneCard.tsx
  src/app/(contents)/mainpage/search/Search.tsx
  src/queries/useActivityQuery.ts
  src/stores/useAllZoneStore.tsx
  src/utils/getUrl.ts
Labels: refactor

#58 fix: 에러 수정
  src/app/components/mypage/MyExperienceManagementList.tsx
Labels: fix

#59 fix: 인풋창 에러 수정
  src/app/components/mypage/UserInfoForm.tsx
Labels: fix

#60 Fix : 메인페이지
  src/app/(contents)/mainpage/main.tsx
  src/app/(contents)/page.tsx
Labels: fix

#61 Fix : 메인페이지
  src/app/components/@shared/footer/Footer.module.scss
  src/app/components/@shared/footer/Footer.tsx
Labels: fix

#62 fix: 대소문자
  src/app/mypage/myexperiencemanagement/page.tsx
Labels: fix

#64 Fix: 예약 캘린더 및 헤더의 반응형 스타일 관련 버그 수정
  .github/workflows/deploy.yml
  build.sh
  src/app/components/@shared/header/Header.module.scss
  src/app/components/reservation/HeadCountStepper.module.scss
  src/app/components/reservation/MobileReservation.module.scss
  src/app/components/reservation/Reservation.module.scss
  src/app/components/reservation/Reservation.tsx
  src/app/components/reservation/ResponsiveReservation.tsx
  src/styles/abstracts/_variables.scss
Labels: fix
